dbl_var <- c(1, 2.5, 4.5)
int_var <- c(1L, 6L, 10L)
log_var <- c(TRUE, FALSE, T, F)
chr_var <- c("these are", "some strings")
a <- c("a", 1)
b <- c(TRUE, 1)
c <- c(1L, 10)
d <- c(a, b, c)
typeof(a); typeof(b); typeof(c); typeof(d)
x <- c(FALSE, FALSE, TRUE)
as.numeric(x)
sum(x)
mean(x)
x <- list(1:3, "a", c(TRUE, FALSE, TRUE), c(2.3, 5.9))
str(x)
type(1:3)
typeof(1:3)
x
str(x)
x <- list(list(list(list())))
str(x)
is.recursive(x)
x <- list(list(1, 2), c(3, 4))
y <- c(list(1, 2), c(3, 4))
str(x)
mtcars
typeof(mtcars)
is.list(mtcars)

mod <- lm(mpg ~ wt, data = mtcars)
mod
help("datasets")
library(help = "datasets")
